### ISSUE TITLE
Generative grammars

### ISSUE THREAD

**Issue by pzelasko** [snipsco/rustling-ontology#129]
Hi there!

I'm wondering whether the parser grammars can be used in a reverse way, as generative grammars (e.g. to generate text sequences which are being parsed by these grammars). Is this a supported feature? If not, do you think it is viable to implement it (and could you suggest where to begin)?

Thanks.

**Comment by rosastern** [comment]
Hi,

This is not a supported feature, and as such generation functionalities would be out of scope of this project.

In principle, the parser grammars can be seen as FSAs which can formally be converted into CFGs, so that might be what you have in mind. However, the rules here are probably too permissive as acceptors in the current context to generate a grammar that would be "good", even if formally correct.

Cheers
